version: "3"

services:
  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile
    image: hot-mapping-vis-server
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./data/capture:/data/capture # volume shared with nginx
    depends_on:
      - api
      - frontend

  frontend:
    build:
      context: ../.
      dockerfile: docker/frontend/Dockerfile.dev
    image: hot-mapping-vis-frontend-dev
    restart: on-failure
    environment:
      - NODE_ENV=development
      - MAPBOX_ACCESS_TOKEN # env passed from shell
    volumes:
      - ./../frontend:/app
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
    ports:
      - "3000:3000"

  renderer:
    build:
      context: ../.
      dockerfile: docker/renderer/Dockerfile.dev
    image: hot-mapping-vis-renderer-dev
    restart: on-failure
    environment:
      - NODE_ENV=development
      - RENDER_QUEUE=render_queue
    depends_on:
      - rabbitmq
    volumes:
      - ./../renderer:/app
      - ./data/capture:/data/capture # volume shared with nginx
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones

  api:
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.dev
    image: hot-mapping-vis-api-dev
    restart: on-failure
    environment:
      - NODE_ENV=development
      - RENDER_QUEUE=render_queue
      - MAILGUN_FROM=visualize@hotosmmail.org
      - MAILGUN_API_KEY # env passed from shell
      - MAILGUN_DOMAIN # env passed from shell
    volumes:
      - ./../api:/app
      - ./data/tiles:/data/tiles
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
    depends_on:
      - db
      - rabbitmq
    ports:
      - "4000:4000"

  db:
    image: mongo
    volumes:
      - ./data/db:/data/db
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "27017" ]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "15672" ]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "15672:15672"
      - "5672:5672"

